### ISSUE TITLE
AttributeError: 'exceptions.AttributeError' object has no attribute 'returncode'

### ISSUE THREAD

**Issue by joseluisq** [edc/bass#35]
```sh
~> python --version
Python 2.6.6

~> rpm --query centos-release
centos-release-6-8.el6.centos.12.3.x86_64

~> bass source ~/.nvm/nvm.sh --no-use ';' nvm install 5
Traceback (most recent call last):
  File "/root/.config/fish/functions/__bass.py", line 77, in <module>
    print('exit code:', e.returncode, file=sys.stderr)
AttributeError: 'exceptions.AttributeError' object has no attribute 'returncode'
```

**Comment by edc** [comment]
@joseluisq The error you saw was because of another error when running nvm. Bass puked when it tries to report the original error. The error reporting should be fixed now. Please download a new version and try again.

**Comment by joseluisq** [comment]
@edc the error persists yet:

```sh
~> bass source ~/.nvm/nvm.sh --no-use ';' nvm install 5
unknown error: 'module' object has no attribute 'check_output'
Traceback (most recent call last):
  File "/root/.config/fish/functions/__bass.py", line 82, in <module>
    script = gen_script()
  File "/root/.config/fish/functions/__bass.py", line 28, in gen_script
    output = subprocess.check_output(args, universal_newlines=True)
AttributeError: 'module' object has no attribute 'check_output'
Bass encountered an error!
```
